### ISSUE TITLE
Switch from Jenkins to Drone CI

### ISSUE THREAD

**Issue by wadells** [gravitational/docker-debian#41]
Collectively, Teleport is moving from Jenkins to Drone.  Docker debian is one of the jobs that needs to be migrated.

## TODO
- [x] Develop a working Drone configuration
- [x] Remove Jenkinfile
- [x] Update documentation
- [x] Enable Drone cron schedule
- [x] Backport to stretch branch
- [x] Backport to jessie branch
- [x] Disable Jenkins jobs

**Comment by wadells** [comment]
I won't be backporting to Jessie because: [in June 2020, LTS support for Jessie ended](https://www.debian.org/releases/jessie/) -- it no longer receives updates.  Instead, the Jenkins -> drone migration will turn off jessie publishing.
